set -e
cd ../ffn
model_params="-n_particles 50 -n_epoch 5000 -fix_variance 0.2"
psvi_config="-lr 1e-3"
dump_prefix='/tmp/dupm'
for width in 5 10 100 # 50 generated by fig1_fig4
do
    for method in 'svgd'
    do
        python bnn_stein_f.py -dataset sine -dump_pred_dir ${dump_prefix}/f${method}${width}.bin $model_params $psvi_config -psvi_method=$method -layers ${width} ${width} -mm_n_particles 400 
        python bnn_stein.py   -dataset sine -dump_pred_dir ${dump_prefix}/${method}${width}.bin  $model_params $psvi_config -psvi_method=$method -layers ${width} ${width}
    done
done
cd ../exps
python synthetic_vis.py -figs 5
